name: CD

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Start Minikube
        uses: medyagh/setup-minikube@v0.0.14

      - name: Build Docker image inside Minikube
        run: |
          eval $(minikube docker-env)
          docker build -t nextflix:latest .

      - name: Deploy to Minikube
        run: kubectl apply -f k8s/


      - name: Port forward and smoke test
        run: |
          sleep 120
          kubectl port-forward svc/nextflix-service 3000:3000 &
          sleep 10
          curl http://localhost:3000
